modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "Apache License Version 2.0"

[[mods]]
modId = "potiontimestacker"
version = "${mod_version}"
displayName = "PotionTimeStacker"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="UltimateFPS.png"
#credits="Thanks for this example mod goes to Java"
authors = "TonimatasDEV"
#displayTest="MATCH_VERSION"

description = '''
Stack potion time.
'''

[[dependencies.potiontimestacker]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.potiontimestacker]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
