modLoader="javafml"
loaderVersion="${forgeVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/TimeStacker/issues"

[[mods]]
modId="timestacker"
version="${modVersion}"
displayName="TimeStacker"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="TonimatasDEV"
#displayTest="MATCH_VERSION"

description='''
Stack potion time.
'''

[[dependencies.timestacker]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.timestacker]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
