modLoader="javafml"
loaderVersion="${forgeVersionRange}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/TimeStacker/issues"

[[mods]]
modId="timestacker"
version="${modVersion}"
displayName="TimeStacker"
logoFile="icon.png"
updateJSONURL="https://api.modrinth.com/updates/timestacker/forge_updates.json"
authors="TonimatasDEV"
description='''
Stack potion time.
'''

[[dependencies.timestacker]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.timestacker]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
