modLoader="javafml"
loaderVersion="[1.0,)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/TimeStacker/issues"
[[mixins]]
config="timestacker-common.mixins.json"

[[mods]]
modId="timestacker"
version="${modVersion}"
displayName="TimeStacker"
logoFile="icon.png"
updateJSONURL="https://api.modrinth.com/updates/timestacker/forge_updates.json"
authors="TonimatasDEV"
description='''
Stack potion time.
'''

[[dependencies.timestacker]]
   modId="neoforge"
   mandatory=true
   versionRange="${neoforgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.timestacker]]
   modId="minecraft"
   mandatory=true
   versionRange="[${minecraftVersion}]"
   ordering="NONE"
   side="BOTH"