name: Build and Upload Artifacts
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TimeStacker-NeoForge
          path: neoforge/build/libs/**.jar

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TimeStacker-Fabric
          path: fabric/build/libs/**.jar
