name: Build and Upload Artifacts
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: PotionTimeStacker-Forge
          path: forge/build/libs/**.jar

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: PotionTimeStacker-Fabric
          path: fabric/build/libs/**.jar