name: Build and Upload Artifacts
on:
  push:
    branches: [1.18.2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload Forge artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: TimeStacker-Forge
          path: forge/build/libs/**.jar

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: TimeStacker-Fabric
          path: fabric/build/libs/**.jar